markdown: kramdown
permalink: /:title.html
url: https://ihaveadrame.github.io
lsi: true
rouge: true
safe: true

# presonal config
title: Alan's Blog
feed: /atom.xml
comments: disqus

author:
  name: alan
  nickname: alan
  email: hao7410521@gmail.com
  gmail: hao7410521@gmail.com
  qqmail: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=GnZzcX94f257WmtrNHl1dw
  qqlist: http://list.qq.com/cgi-bin/qf_invite?id=eff06957927177ae5d491bb3c18e4a3c5fc328c95b6ae04f
  site: https://ihaveadrame.github.io

seo:
  keyword:
  description:
